<!DOCTYPE html>
<html lang="pt-BR">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>My Application</title>


       
    </head>

    <body>

       <h1>My Application</h1>
       
       <div>
       	<?php echo $this->content; ?>
       </div>
       
    </body>

</html>
